apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-k8s-deployment
  labels:
    app: demo-k8s-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-k8s-app
  template:
    metadata:
      labels:
        app: demo-k8s-app
    spec:
      containers:
      - name: demo-k8s-container
        image: your-dockerhub-username/demo-k8s-repo:latest
        ports:
        - containerPort: 8080
